#!/usr/bin/env bash
# Compile the native SwiftUI control panel into gui/AgentBus.app.
# Needs only the Xcode Command Line Tools — no Xcode project, no Electron.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
GUI="$ROOT/gui"
APP="$GUI/AgentBus.app"
NODE="$(command -v node)"

[[ -f "$ROOT/dist/cli.js" ]] || { echo "build the broker first: (cd '$ROOT' && npm run build)" >&2; exit 1; }

# Bake the local paths the app needs to launch the broker itself.
cat > "$GUI/Sources/AppPaths.swift" <<EOF
// Generated by scripts/build-gui.sh — do not edit.
enum AppPaths {
    static let node = "$NODE"
    static let cli = "$ROOT/dist/cli.js"
}
EOF

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>AgentBus</string>
  <key>CFBundleDisplayName</key><string>Qagent</string>
  <key>CFBundleIdentifier</key><string>local.agentbus.controlpanel</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>AgentBus</string>
  <key>LSMinimumSystemVersion</key><string>14.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>NSAppTransportSecurity</key>
  <dict><key>NSAllowsLocalNetworking</key><true/></dict>
</dict>
</plist>
EOF

echo "compiling…"
swiftc -parse-as-library -O \
  "$GUI/Sources/App.swift" \
  "$GUI/Sources/AppPaths.swift" \
  "$GUI/Sources/Models.swift" \
  "$GUI/Sources/BusClient.swift" \
  "$GUI/Sources/ContentView.swift" \
  "$GUI/Sources/Compose.swift" \
  -o "$APP/Contents/MacOS/AgentBus"

# Ad-hoc signature so macOS will run it and remember window state.
codesign --force --sign - "$APP" >/dev/null 2>&1 || true

echo "built $APP"
echo "run it:  open '$APP'"
