import { spawn } from "node:child_process";
import { randomBytes } from "node:crypto";
import { createServer, IncomingMessage, Server, ServerResponse } from "node:http";
import { existsSync, mkdirSync, openSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { discoverHarnessModels, probeHarness } from "./adapters.js";
import { AgentDefinition, BusConfig, DEFAULT_CONFIG_PATH, loadConfig, resolveAgent, validateConfig } from "./config.js";
import { addOrUpdateIntegration, IntegrationInput } from "./integrations.js";
import { Agent, BUS_HOME, BUS_HOST, BUS_PORT, MAX_WAIT_MS, Run, Task } from "./protocol.js";
import { OPERATOR_TOKEN_PATH, agentTokenPath, hashToken, readTokenFile, writePrivateToken } from "./security.js";
import { BrokerOptions, BrokerService } from "./broker.js";

const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");
const CLI_PATH=join(ROOT,"cli.js");
const DEFAULT_STATIC_ROOT=join(ROOT,"dist","web");
const PROJECT_META_KEY="dashboard.projects";
const SESSION_TTL_MS=24*60*60_000;
const LOGIN_TICKET_TTL_MS=60_000;
export const DASHBOARD_URL=`http://${BUS_HOST}:${BUS_PORT}`;

export interface ProductServerOptions extends BrokerOptions{staticRoot?:string}
export interface ProductServerHandle{service:BrokerService;server:Server;host:string;port:number;url:string;close():Promise<void>}
interface ProjectRecord{path:string;name:string;createdAt:number;lastUsedAt:number}
class BrowserAuthError extends Error{}

class BrowserSessions{
  private tickets=new Map<string,number>(); private sessions=new Map<string,number>();
  private prune(){const now=Date.now();for(const [k,v] of this.tickets)if(v<=now)this.tickets.delete(k);for(const [k,v] of this.sessions)if(v<=now)this.sessions.delete(k)}
  issue(){this.prune();const ticket=randomBytes(24).toString("base64url");this.tickets.set(ticket,Date.now()+LOGIN_TICKET_TTL_MS);return{ticket,expiresInSeconds:LOGIN_TICKET_TTL_MS/1000}}
  exchange(ticket:string){this.prune();const expiry=this.tickets.get(ticket);this.tickets.delete(ticket);if(!expiry||expiry<=Date.now())throw new BrowserAuthError("login ticket is invalid or expired");const session=randomBytes(32).toString("base64url");this.sessions.set(session,Date.now()+SESSION_TTL_MS);return session}
  valid(session:string){this.prune();const expiry=this.sessions.get(session);return Boolean(expiry&&expiry>Date.now())}
  revoke(session:string){this.sessions.delete(session)}
}

function cookies(req:IncomingMessage){const out:Record<string,string>={};for(const piece of (req.headers.cookie??"").split(";")){const i=piece.indexOf("=");if(i>0)out[piece.slice(0,i).trim()]=decodeURIComponent(piece.slice(i+1).trim())}return out}
function requireSession(req:IncomingMessage,sessions:BrowserSessions){const session=cookies(req).agent_bus_session??"";if(!session||!sessions.valid(session))throw new BrowserAuthError("dashboard session missing or expired; run `agent-bus open`");return session}
function requireSameOrigin(req:IncomingMessage){const origin=req.headers.origin,host=req.headers.host;if(!origin||!host)throw new BrowserAuthError("same-origin request required");if(origin!==`http://${host}`&&origin!==`https://${host}`)throw new BrowserAuthError("cross-origin dashboard request rejected")}
function readJson(req:IncomingMessage):Promise<Record<string,unknown>>{return new Promise((done,reject)=>{const chunks:Buffer[]=[];let size=0;req.on("data",(chunk:Buffer)=>{size+=chunk.length;if(size>2*1024*1024){reject(new Error("request body exceeds 2 MiB"));req.destroy();return}chunks.push(chunk)});req.on("error",reject);req.on("end",()=>{const raw=Buffer.concat(chunks).toString("utf8");if(!raw)return done({});try{const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error("body must be a JSON object");done(parsed)}catch(e){reject(new Error(`invalid JSON body: ${(e as Error).message}`))}})})}
function sendJson(res:ServerResponse,status:number,payload:unknown,headers:Record<string,string>={}){const body=JSON.stringify(payload);res.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":String(Buffer.byteLength(body)),"cache-control":"no-store","x-content-type-options":"nosniff",...headers});res.end(body)}
function errorStatus(error:unknown){if(error instanceof BrowserAuthError)return 401;const m=String((error as Error)?.message??error);if(m.startsWith("unauthorized"))return 401;if(m.includes("not authorized")||m.startsWith("only "))return 403;if(m.startsWith("no route")||m.startsWith("unknown run")||m.startsWith("unknown task"))return 404;if(m.includes("already")||m.includes("not submitted")||m.includes("not eligible"))return 409;return 400}
function typeOf(path:string){const ext=extname(path).toLowerCase();return ext===".js"||ext===".mjs"?"text/javascript; charset=utf-8":ext===".css"?"text/css; charset=utf-8":ext===".svg"?"image/svg+xml":ext===".json"?"application/json; charset=utf-8":ext===".woff2"?"font/woff2":"text/html; charset=utf-8"}
function serveStatic(req:IncomingMessage,res:ServerResponse,staticRoot:string,pathname:string){if(req.method!=="GET"&&req.method!=="HEAD")return sendJson(res,405,{error:"method not allowed"});const root=resolve(staticRoot);const requested=pathname==="/"?"index.html":decodeURIComponent(pathname).replace(/^\/+/,"");let target=resolve(root,requested);if(target!==root&&!target.startsWith(root+sep))return sendJson(res,404,{error:"not found"});if(!existsSync(target)||!statSync(target).isFile())target=join(root,"index.html");if(!existsSync(target))return sendJson(res,503,{error:"dashboard build missing; run `npm run build`"});const body=readFileSync(target);res.writeHead(200,{"content-type":typeOf(target),"content-length":String(body.length),"cache-control":target.endsWith("index.html")?"no-store":"public, max-age=31536000, immutable","x-content-type-options":"nosniff","x-frame-options":"DENY","referrer-policy":"no-referrer","content-security-policy":"default-src 'self'; script-src 'self'; style-src 'self'; connect-src 'self'; img-src 'self' data:; font-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'"});req.method==="HEAD"?res.end():res.end(body)}
function operatorToken(path:string){const token=readTokenFile(path);if(!token)throw new Error(`operator token missing at ${path}`);return token}
function verifyOperatorToken(service:BrokerService,token:string){const identity=token?service.store.identityByTokenHash(hashToken(token)):null;if(!identity||identity.authority!=="operator")throw new BrowserAuthError("invalid operator credential")}

function permissions(value:unknown,fallback?:AgentDefinition["permissions"]):AgentDefinition["permissions"]{const row=value&&typeof value==="object"?value as Record<string,unknown>:{};const fs=["none","read","write"].includes(String(row.filesystem))?String(row.filesystem) as "none"|"read"|"write":fallback?.filesystem??"read";return{canDelegate:row.canDelegate===undefined?fallback?.canDelegate??false:Boolean(row.canDelegate),canReview:row.canReview===undefined?fallback?.canReview??false:Boolean(row.canReview),filesystem:fs,shell:row.shell===undefined?fallback?.shell??false:Boolean(row.shell),network:row.network===undefined?fallback?.network??false:Boolean(row.network),maxDelegationDepth:Math.max(0,Number(row.maxDelegationDepth??fallback?.maxDelegationDepth??0)||0),allowedPaths:Array.isArray(row.allowedPaths)?row.allowedPaths.map(String).filter(Boolean):fallback?.allowedPaths??["."]}}
function saveAgent(configPath:string,body:Record<string,unknown>){const config=structuredClone(loadConfig(configPath));const id=String(body.id??"").trim();if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]{0,63}$/.test(id))throw new Error("agent id must be 1-64 safe characters");const existing=config.agents[id],modelId=String(body.model??existing?.model??""),role=String(body.role??existing?.role??"");const model=config.models[modelId];if(!model)throw new Error(`unknown model: ${modelId}`);if(!config.roles[role])throw new Error(`unknown role: ${role}`);if(body.modelFamily!==undefined)model.family=String(body.modelFamily).trim()||model.family;if(body.exactModel!==undefined){const exact=String(body.exactModel).trim();if(exact)model.exactModel=exact;else delete model.exactModel}const authority=String(body.authority??existing?.authority??(role==="manager"?"manager":"worker"));if(authority!=="manager"&&authority!=="worker")throw new Error("agent authority must be manager or worker");const harnessOptions={...(existing?.harnessOptions??{})};if(body.harnessOptions&&typeof body.harnessOptions==="object")Object.assign(harnessOptions,body.harnessOptions);if(body.reasoning!==undefined)harnessOptions.reasoning=String(body.reasoning);if(body.effort!==undefined)harnessOptions.effort=String(body.effort);const agent:AgentDefinition={id,model:modelId,role,authority,description:String(body.description??existing?.description??`${role} agent`),enabled:body.enabled===undefined?existing?.enabled??true:Boolean(body.enabled),autoStart:body.autoStart===undefined?existing?.autoStart??false:Boolean(body.autoStart),permissions:permissions(body.permissions,existing?.permissions),harnessOptions};config.agents[id]=agent;validateConfig(config);writeFileSync(configPath,`${JSON.stringify(config,null,2)}\n`);return{agent,config}}
function applyConfig(service:BrokerService,config:BusConfig){Object.assign(service.config,config);const configured=new Set(Object.keys(config.agents));for(const [id,def] of Object.entries(config.agents)){const resolved=resolveAgent(config,id),old=service.agents.get(id);const agent:Agent={id,role:def.role,model:resolved.modelDefinition.id,family:resolved.modelDefinition.family,provider:resolved.modelDefinition.provider,harness:resolved.harnessDefinition.id,description:def.description,auth:resolved.providerDefinition.authSource,authority:def.authority,permissions:def.permissions,status:old?.status??"offline",currentTaskId:old?.currentTaskId??null,registeredAt:old?.registeredAt??0,lastSeen:old?.lastSeen??0};service.agents.set(id,agent);service.store.saveAgent(agent);const identity=service.store.identityById(id);if(identity)service.store.upsertIdentity({...identity,authority:def.authority,permissions:def.permissions,updatedAt:Date.now()})}for(const [id,agent] of service.agents){if(id!=="operator"&&!configured.has(id)){agent.status="offline";service.store.saveAgent(agent)}}}

function storedProjects(service:BrokerService):ProjectRecord[]{try{return JSON.parse(service.store.getMeta(PROJECT_META_KEY)??"[]")}catch{return[]}}
function projects(service:BrokerService){const map=new Map<string,ProjectRecord>();for(const p of storedProjects(service))map.set(p.path,p);for(const run of service.runs.values()){const old=map.get(run.projectRoot);map.set(run.projectRoot,{path:run.projectRoot,name:old?.name??(basename(run.projectRoot)||run.projectRoot),createdAt:old?.createdAt??run.createdAt,lastUsedAt:Math.max(old?.lastUsedAt??0,run.updatedAt)})}return[...map.values()].sort((a,b)=>b.lastUsedAt-a.lastUsedAt)}
function rememberProject(service:BrokerService,value:unknown){const path=resolve(String(value??"").trim());if(!path||!existsSync(path)||!statSync(path).isDirectory())throw new Error(`project root is not a directory: ${path}`);const now=Date.now(),list=storedProjects(service),old=list.find(x=>x.path===path);const project:ProjectRecord={path,name:old?.name??(basename(path)||path),createdAt:old?.createdAt??now,lastUsedAt:now};service.store.setMeta(PROJECT_META_KEY,JSON.stringify([project,...list.filter(x=>x.path!==path)].slice(0,100)));return project}
async function ensureAgentToken(service:BrokerService,operatorTokenPath:string,id:string){const path=agentTokenPath(id),existing=readTokenFile(path);if(existing)return existing;const token=operatorToken(operatorTokenPath);let result=await service.handle("/agent/provision",{token,id,rotate:false}) as {token:string|null};if(!result.token)result=await service.handle("/agent/provision",{token,id,rotate:true}) as {token:string|null};if(!result.token)throw new Error(`could not provision ${id}`);writePrivateToken(path,result.token);return result.token}
async function startAgent(service:BrokerService,operatorTokenPath:string,id:string,requested?:string){const def=service.config.agents[id];if(!def)throw new Error(`unknown configured agent: ${id}`);if(!def.enabled)throw new Error(`agent ${id} is disabled`);const live=service.supervisorMeta.get(id);if(live)return{id,started:false,pid:live.pid,message:"already supervised"};const latestRun=[...service.runs.values()].sort((a,b)=>b.updatedAt-a.updatedAt)[0],latestProject=projects(service)[0];const root=resolve(String(requested||latestRun?.projectRoot||latestProject?.path||""));if(!root||!existsSync(root)||!statSync(root).isDirectory())throw new Error("a valid projectRoot is required to start an agent");await ensureAgentToken(service,operatorTokenPath,id);mkdirSync(join(BUS_HOME,"logs"),{recursive:true});const log=openSync(join(BUS_HOME,"logs",`${id}.out`),"a");const child=spawn(process.execPath,[CLI_PATH,"supervise",id,root],{detached:true,stdio:["ignore",log,log]});child.unref();return{id,started:true,pid:child.pid??0,projectRoot:root}}
async function stopRun(service:BrokerService,token:string,runId:string,reason:string){const run=service.runs.get(runId);if(!run)throw new Error(`unknown run: ${runId}`);if(run.status==="active"){run.status="cancelled";run.updatedAt=Date.now();service.store.saveRun(run);for(const task of [...service.tasks.values()].filter(t=>t.runId===runId&&!["accepted","failed","cancelled"].includes(t.state)))await service.handle("/task/cancel",{token,taskId:task.id,reason});run.updatedAt=Date.now();service.store.saveRun(run)}return{run,tasks:[...service.tasks.values()].filter(t=>t.runId===runId)}}
async function providerStatus(service:BrokerService,discover:boolean){const config=service.config;const harnessRows=new Map<string,any>();for(const harness of Object.values(config.harnesses)){const agentDef=Object.values(config.agents).find(a=>config.models[a.model]?.harness===harness.id);let cliFound=false,version:string|null=null,error:string|null=harness.enabled?"no configured agent uses this harness":"disabled",models:string[]=[];if(harness.enabled&&agentDef){const resolved=resolveAgent(config,agentDef.id),probe=await probeHarness(resolved);cliFound=probe.available;version=probe.version;error=probe.error;if(discover&&probe.available&&harness.modelDiscovery){const d=await discoverHarnessModels(resolved);models=d.models;if(d.error)error=d.error}}harnessRows.set(harness.id,{id:harness.id,configured:harness.enabled,command:harness.command,cliFound,version,error,liveVerification:harness.id==="fake"?"not-required":"unknown",discoveredModels:models})}return Object.values(config.providers).map(p=>{const harnesses=Object.values(config.harnesses).filter(h=>h.providers.includes(p.id)).map(h=>harnessRows.get(h.id));return{id:p.id,displayName:p.displayName,configured:p.enabled&&harnesses.some(h=>h?.configured),cliFound:harnesses.some(h=>h?.cliFound),authKind:p.authKind,authSource:p.authSource,subscriptionBacked:p.subscriptionBacked,liveVerification:p.id==="fake"?"not-required":"unknown",harnesses}})}

async function handleApi(req:IncomingMessage,res:ServerResponse,pathname:string,params:URLSearchParams,service:BrokerService,sessions:BrowserSessions,operatorTokenPath:string,configPath:string|null){
  if(pathname==="/api/session"&&req.method==="POST"){requireSameOrigin(req);const body=await readJson(req),session=sessions.exchange(String(body.ticket??""));return sendJson(res,200,{authenticated:true},{"set-cookie":`agent_bus_session=${encodeURIComponent(session)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${SESSION_TTL_MS/1000}`})}
  const session=requireSession(req,sessions);if(req.method&&req.method!=="GET"&&req.method!=="HEAD")requireSameOrigin(req);
  if(pathname==="/api/session"&&req.method==="GET")return sendJson(res,200,{authenticated:true});if(pathname==="/api/session/logout"&&req.method==="POST"){sessions.revoke(session);return sendJson(res,200,{authenticated:false},{"set-cookie":"agent_bus_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"})}
  if(pathname==="/api/events"&&req.method==="GET"){res.writeHead(200,{"content-type":"text/event-stream; charset=utf-8","cache-control":"no-cache, no-transform",connection:"keep-alive","x-accel-buffering":"no"});res.write(": connected\n\n");let since=Math.max(0,Number(params.get("since")??0)||0),closed=false,running=false;const tick=async()=>{if(closed||running)return;running=true;try{const snap=await service.handle("/snapshot",{sinceSeq:since}) as any;since=Number(snap.seq??since);res.write(`event: snapshot\ndata: ${JSON.stringify({...snap,incremental:true})}\n\n`)}catch(e){res.write(`event: error\ndata: ${JSON.stringify({error:(e as Error).message})}\n\n`)}finally{running=false}};await tick();const timer=setInterval(tick,800);timer.unref();req.on("close",()=>{closed=true;clearInterval(timer)});return}
  if(pathname==="/api/state"&&req.method==="GET")return sendJson(res,200,await service.handle("/snapshot",{sinceSeq:0}));if(pathname==="/api/catalog"&&req.method==="GET")return sendJson(res,200,await service.handle("/catalog",{}));if(pathname==="/api/projects"&&req.method==="GET")return sendJson(res,200,{projects:projects(service)});if(pathname==="/api/projects"&&req.method==="POST"){const body=await readJson(req);return sendJson(res,200,{project:rememberProject(service,body.path??body.projectRoot)})}if(pathname==="/api/providers/status"&&req.method==="GET")return sendJson(res,200,{providers:await providerStatus(service,params.get("discover")==="1")});if(pathname==="/api/runs"&&req.method==="GET")return sendJson(res,200,await service.handle("/run/list",{}));if(pathname==="/api/runs"&&req.method==="POST"){const body=await readJson(req);rememberProject(service,body.projectRoot);return sendJson(res,200,await service.handle("/run/create",{...body,token:operatorToken(operatorTokenPath)}))}
  const run=pathname.match(/^\/api\/runs\/([^/]+)$/);if(run&&req.method==="GET")return sendJson(res,200,await service.handle("/run/get",{runId:decodeURIComponent(run[1])}));const stop=pathname.match(/^\/api\/runs\/([^/]+)\/stop$/);if(stop&&req.method==="POST"){const body=await readJson(req);return sendJson(res,200,await stopRun(service,operatorToken(operatorTokenPath),decodeURIComponent(stop[1]),String(body.reason??"Run stopped by operator.")))}
  if(pathname==="/api/messages"&&req.method==="POST"){const body=await readJson(req);return sendJson(res,200,await service.handle("/send",{...body,token:operatorToken(operatorTokenPath)}))}if(pathname==="/api/tasks"&&req.method==="POST"){const body=await readJson(req);return sendJson(res,200,await service.handle("/task/create",{...body,token:operatorToken(operatorTokenPath)}))}const task=pathname.match(/^\/api\/tasks\/([^/]+)\/(review|cancel)$/);if(task&&req.method==="POST"){const body=await readJson(req);return sendJson(res,200,await service.handle(task[2]==="review"?"/task/review":"/task/cancel",{...body,taskId:decodeURIComponent(task[1]),token:operatorToken(operatorTokenPath)}))}
  if(pathname==="/api/agents"&&req.method==="POST"){if(!configPath)throw new Error("agent configuration editing is unavailable with an in-memory config");const result=saveAgent(configPath,await readJson(req));applyConfig(service,result.config);return sendJson(res,200,{agent:result.agent,applied:true})}if(pathname==="/api/integrations"&&req.method==="POST"){if(!configPath)throw new Error("integration editing is unavailable with an in-memory config");const result=addOrUpdateIntegration(configPath,await readJson(req) as unknown as IntegrationInput);applyConfig(service,result.config);return sendJson(res,200,{provider:result.provider,harness:result.harness,model:result.model,agent:result.agent,applied:true})}
  if(pathname==="/api/agents/stop-all"&&req.method==="POST"){const token=operatorToken(operatorTokenPath),results:any[]=[];for(const [id] of [...service.supervisorMeta]){try{results.push({id,...await service.handle("/kill",{token,agentId:id}) as any})}catch(e){results.push({id,ok:false,error:(e as Error).message})}}return sendJson(res,200,{results})}const action=pathname.match(/^\/api\/agents\/([^/]+)\/(start|stop)$/);if(action&&req.method==="POST"){const id=decodeURIComponent(action[1]);if(action[2]==="start"){const body=await readJson(req);return sendJson(res,200,await startAgent(service,operatorTokenPath,id,body.projectRoot?String(body.projectRoot):undefined))}return sendJson(res,200,await service.handle("/kill",{token:operatorToken(operatorTokenPath),agentId:id}))}
  return sendJson(res,404,{error:"dashboard route not found"})
}

export async function startProductServer(options:ProductServerOptions={}):Promise<ProductServerHandle>{const service=new BrokerService(options),host=options.host??BUS_HOST,requestedPort=options.port??BUS_PORT,operatorTokenPath=options.operatorTokenPath??OPERATOR_TOKEN_PATH,configPath=options.configPath??(options.config?null:(process.env.AGENT_BUS_CONFIG??DEFAULT_CONFIG_PATH)),staticRoot=options.staticRoot??DEFAULT_STATIC_ROOT,sessions=new BrowserSessions();const server=createServer(async(req,res)=>{const url=new URL(req.url??"/",`http://${req.headers.host??`${host}:${requestedPort}`}`),pathname=url.pathname;if(pathname==="/health")return sendJson(res,200,{ok:true,pid:process.pid,agents:service.agents.size,tasks:service.tasks.size,runs:service.runs.size,durable:true,dashboard:true,uiBuilt:existsSync(join(staticRoot,"index.html"))});try{if(pathname==="/dashboard/login"&&req.method==="POST"){const body=await readJson(req);verifyOperatorToken(service,String(body.token??""));return sendJson(res,200,{...sessions.issue(),dashboardUrl:DASHBOARD_URL})}if(pathname.startsWith("/api/"))return await handleApi(req,res,pathname,url.searchParams,service,sessions,operatorTokenPath,configPath);if((req.method==="GET"||req.method==="HEAD")&&!pathname.startsWith("/agent/")&&pathname!=="/register")return serveStatic(req,res,staticRoot,pathname);if(req.method!=="POST")return sendJson(res,405,{error:"legacy broker routes require POST"});return sendJson(res,200,await service.handle(pathname,await readJson(req)))}catch(e){return sendJson(res,errorStatus(e),{error:(e as Error).message})}});server.headersTimeout=MAX_WAIT_MS+60_000;server.requestTimeout=0;server.keepAliveTimeout=MAX_WAIT_MS+60_000;await new Promise<void>((done,reject)=>{server.once("error",reject);server.listen(requestedPort,host,()=>done())});const address=server.address(),port=typeof address==="object"&&address?address.port:requestedPort,url=`http://${host}:${port}`;process.stderr.write(`agent-bus listening on ${url} (dashboard + API + broker, SQLite: ${service.store.path})\n`);return{service,server,host,port,url,close:()=>new Promise<void>((done,reject)=>server.close(error=>{service.close();error?reject(error):done()}))}}
