const state={snapshot:{roster:[],tasks:[],runs:[],messages:[],seq:0,pathLeases:[]},catalog:null,selectedRunId:null,selectedTaskId:null,providerProbes:[]};
const $=(id)=>document.getElementById(id);
const escapeHtml=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const fmtTime=(ts)=>new Date(Number(ts)||Date.now()).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});
const fmtAgo=(ts)=>{const s=Math.max(0,Math.round((Date.now()-Number(ts||0))/1000));return s<60?`${s}s`:s<3600?`${Math.round(s/60)}m`:`${Math.round(s/3600)}h`};
let toastTimer;function toast(message){const el=$('toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3200)}
async function api(path,options={}){const res=await fetch(path,{credentials:'same-origin',headers:{'content-type':'application/json',...(options.headers||{})},...options});const text=await res.text();const body=text?JSON.parse(text):{};if(!res.ok)throw new Error(body.error||`HTTP ${res.status}`);return body}
function selectedRun(){return state.snapshot.runs.find(r=>r.id===state.selectedRunId)||null}
function selectedTasks(){return state.selectedRunId?state.snapshot.tasks.filter(t=>t.runId===state.selectedRunId):state.snapshot.tasks}
function renderRuns(){const box=$('runs');box.innerHTML=state.snapshot.runs.map(r=>`<div class="run-item ${r.id===state.selectedRunId?'active':''}" data-run="${escapeHtml(r.id)}"><strong>${escapeHtml(r.goal)}</strong><small>${escapeHtml(r.status)} · ${escapeHtml(r.projectRoot?.split('/').pop()||r.projectRoot)} · ${fmtAgo(r.updatedAt)}</small></div>`).join('')||'<div class="muted" style="padding:8px">No runs yet.</div>';box.querySelectorAll('[data-run]').forEach(el=>el.onclick=()=>{state.selectedRunId=el.dataset.run;render()})}
function renderProviders(){if(!state.catalog){$('providers').innerHTML='<div class="muted">loading…</div>';return}const probeByHarness=new Map(state.providerProbes.map(p=>[p.harness,p]));const providers=Object.values(state.catalog.providers||{});$('providers').innerHTML=providers.map(p=>{const harnesses=Object.values(state.catalog.harnesses||{}).filter(h=>h.providers.includes(p.id));const available=harnesses.some(h=>probeByHarness.get(h.id)?.available);const configured=harnesses.some(h=>h.enabled);return `<div class="provider-item"><span><span class="dot ${available?'on':''}"></span>${escapeHtml(p.displayName)}</span><small>${available?'ready':configured?'configured':'off'}</small></div>`}).join('')}
function renderHeader(){const run=selectedRun();const h=$('runHeader');if(!run){h.className='run-header empty-state';h.innerHTML='<div><div class="eyebrow">CONTROL ROOM</div><h1>No run selected</h1><p>Create a run or select one from the sidebar.</p></div>';return}h.className='run-header';h.innerHTML=`<div><div class="eyebrow">${escapeHtml(run.status).toUpperCase()} · ${escapeHtml(run.id)}</div><h1>${escapeHtml(run.goal)}</h1><p>${escapeHtml(run.projectRoot)}</p></div><div class="muted">updated ${fmtAgo(run.updatedAt)} ago</div>`}
function renderTasks(){const tasks=selectedTasks().sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));$('taskCount').textContent=tasks.length;$('tasks').innerHTML=tasks.map(t=>`<div class="task" style="--depth:${Math.min(6,t.depth||0)}" data-task="${escapeHtml(t.id)}" data-state="${escapeHtml(t.state)}"><div class="task-title">${escapeHtml(t.title)}</div><div class="task-meta"><span class="state">${escapeHtml(t.state)}</span><span>${escapeHtml(t.assignee||'?')}</span><span>${escapeHtml(t.role)} · c${escapeHtml(t.complexity)}</span><span>r${escapeHtml(t.round)}</span><span>${fmtAgo(t.updatedAt)}</span></div></div>`).join('')||'<div class="muted" style="padding:16px">No tasks.</div>';$('tasks').querySelectorAll('[data-task]').forEach(el=>el.onclick=()=>openTask(el.dataset.task))}
function renderMessages(){const runTasks=new Set(selectedTasks().map(t=>t.id));let msgs=state.snapshot.messages;if(state.selectedRunId)msgs=msgs.filter(m=>!m.taskId||runTasks.has(m.taskId));msgs=[...msgs].sort((a,b)=>(b.seq||0)-(a.seq||0));$('messageCount').textContent=msgs.length;$('messages').innerHTML=msgs.slice(0,300).map(m=>`<div class="message"><div class="message-top"><strong>${escapeHtml(m.from)}</strong><span>→</span><strong>${escapeHtml(m.to)}</strong><span>${escapeHtml(m.type)}</span><span>${fmtTime(m.ts)}</span></div><div class="message-subject">${escapeHtml(m.subject)}</div><div class="message-body">${escapeHtml(m.body)}</div></div>`).join('')||'<div class="muted" style="padding:16px">No activity yet.</div>'}
function statusDot(agent){if(agent.stalled)return'error';if(agent.status==='working')return'working';if(agent.status==='idle'||agent.status==='waiting')return'on';return''}
function renderAgents(){const agents=state.snapshot.roster.filter(a=>a.id!=='operator');$('agentCount').textContent=agents.length;$('agents').innerHTML=agents.map(a=>`<div class="agent"><div class="agent-row"><div><span class="dot ${statusDot(a)}"></span><span class="agent-name">${escapeHtml(a.id)}</span></div><span class="agent-status">${escapeHtml(a.stalled?'stalled':a.status)}</span></div><div class="agent-meta">${escapeHtml(a.provider)} · ${escapeHtml(a.family)}/${escapeHtml(a.model)} · ${escapeHtml(a.harness)}</div><div class="agent-actions">${a.supervisorPid?`<button class="agent-stop" data-id="${escapeHtml(a.id)}">Stop</button>`:`<button class="agent-start" data-id="${escapeHtml(a.id)}">Start</button>`}<button class="agent-edit" data-id="${escapeHtml(a.id)}">Edit</button></div></div>`).join('')||'<div class="muted" style="padding:10px">No configured agents.</div>';$('agents').querySelectorAll('.agent-stop').forEach(b=>b.onclick=()=>stopAgent(b.dataset.id));$('agents').querySelectorAll('.agent-start').forEach(b=>b.onclick=()=>startAgent(b.dataset.id));$('agents').querySelectorAll('.agent-edit').forEach(b=>b.onclick=()=>openAgent(b.dataset.id));const select=$('messageTo');const current=select.value;select.innerHTML='<option value="*">everyone</option>'+agents.map(a=>`<option value="${escapeHtml(a.id)}">${escapeHtml(a.id)}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current}
function render(){if(!state.selectedRunId&&state.snapshot.runs.length)state.selectedRunId=state.snapshot.runs[0].id;renderRuns();renderProviders();renderHeader();renderTasks();renderMessages();renderAgents()}
function applySnapshot(next){if(next.incremental){const byId=new Map(state.snapshot.messages.map(m=>[m.id,m]));for(const m of next.messages||[])byId.set(m.id,m);state.snapshot={...state.snapshot,...next,messages:[...byId.values()].sort((a,b)=>(a.seq||0)-(b.seq||0))};if(state.snapshot.messages.length>5000)state.snapshot.messages=state.snapshot.messages.slice(-5000)}else state.snapshot=next;render()}
async function load(){const [snapshot,catalog]=await Promise.all([api('/api/state'),api('/api/catalog')]);state.snapshot=snapshot;state.catalog=catalog;render();api('/api/providers/status').then(r=>{state.providerProbes=r.probes||[];renderProviders()}).catch(()=>{});const events=new EventSource('/api/events',{withCredentials:true});events.addEventListener('snapshot',e=>{try{applySnapshot(JSON.parse(e.data));$('connection').textContent='live'}catch{}});events.addEventListener('error',()=>{$('connection').textContent='reconnecting…'})}
async function startAgent(id){try{const run=selectedRun();await api(`/api/agents/${encodeURIComponent(id)}/start`,{method:'POST',body:JSON.stringify({projectRoot:run?.projectRoot||''})});toast(`${id} starting`)}catch(e){toast(e.message)}}
async function stopAgent(id){try{await api(`/api/agents/${encodeURIComponent(id)}/stop`,{method:'POST',body:'{}'});toast(`${id} stopped`)}catch(e){toast(e.message)}}
function openAgent(id=null){if(!state.catalog)return;const def=id?state.catalog.agents[id]:null;$('agentId').value=def?.id||'';$('agentDescription').value=def?.description||'';$('agentFilesystem').value=def?.permissions?.filesystem||'read';$('agentShell').checked=!!def?.permissions?.shell;$('agentNetwork').checked=!!def?.permissions?.network;$('agentReview').checked=!!def?.permissions?.canReview;$('agentDelegate').checked=!!def?.permissions?.canDelegate;$('agentAutoStart').checked=!!def?.autoStart;$('agentModel').innerHTML=Object.values(state.catalog.models||{}).map(m=>`<option value="${escapeHtml(m.id)}">${escapeHtml(m.id)} · ${escapeHtml(m.provider)}/${escapeHtml(m.family)}</option>`).join('');$('agentRole').innerHTML=Object.values(state.catalog.roles||{}).map(r=>`<option value="${escapeHtml(r.id)}">${escapeHtml(r.id)}</option>`).join('');if(def){$('agentModel').value=def.model;$('agentRole').value=def.role}$('agentDialog').showModal()}
function openTask(id){const t=state.snapshot.tasks.find(x=>x.id===id);if(!t)return;state.selectedTaskId=id;$('taskDialogTitle').textContent=t.title;$('taskFeedback').value='';$('taskDetail').innerHTML=`<div class="detail-block"><h3>State</h3><pre>${escapeHtml(`${t.state} · ${t.assigner} → ${t.assignee||'?'} · ${t.role}/c${t.complexity}`)}</pre></div><div class="detail-block"><h3>Brief</h3><pre>${escapeHtml(t.brief||'')}</pre></div>${t.result?`<div class="detail-block"><h3>Result</h3><pre>${escapeHtml(t.result.summary||'')}</pre></div>`:''}${t.routing?.reason?`<div class="detail-block"><h3>Routing</h3><pre>${escapeHtml(t.routing.reason)}</pre></div>`:''}`;$('acceptTaskBtn').disabled=t.state!=='submitted';$('requestChangesBtn').disabled=t.state!=='submitted';$('taskDialog').showModal()}
$('newRunBtn').onclick=()=>$('runDialog').showModal();$('addAgentBtn').onclick=()=>openAgent();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('runForm').onsubmit=async(e)=>{e.preventDefault();try{const result=await api('/api/runs',{method:'POST',body:JSON.stringify({projectRoot:$('projectRoot').value,goal:$('runGoal').value})});state.selectedRunId=result.run.id;$('runDialog').close();toast(`run ${result.run.id} started`)}catch(err){toast(err.message)}};
$('agentForm').onsubmit=async(e)=>{e.preventDefault();const role=$('agentRole').value;try{await api('/api/agents',{method:'POST',body:JSON.stringify({id:$('agentId').value,model:$('agentModel').value,role,authority:role==='manager'?'manager':'worker',description:$('agentDescription').value,enabled:true,autoStart:$('agentAutoStart').checked,permissions:{canDelegate:$('agentDelegate').checked,canReview:$('agentReview').checked,filesystem:$('agentFilesystem').value,shell:$('agentShell').checked,network:$('agentNetwork').checked,maxDelegationDepth:$('agentDelegate').checked?4:0,allowedPaths:['.']}})});$('agentDialog').close();toast('Agent saved. Restart Agent Bus to load registry changes.')}catch(err){toast(err.message)}};
$('messageForm').onsubmit=async(e)=>{e.preventDefault();const text=$('messageText').value.trim();if(!text)return;try{await api('/api/messages',{method:'POST',body:JSON.stringify({to:$('messageTo').value,subject:text.slice(0,100),body:text,type:'info'})});$('messageText').value=''}catch(err){toast(err.message)}};
$('stopAllBtn').onclick=async()=>{if(!confirm('Stop every running agent?'))return;try{await api('/api/agents/stop-all',{method:'POST',body:'{}'});toast('All supervisors stopped')}catch(e){toast(e.message)}};
$('acceptTaskBtn').onclick=()=>reviewTask(true);$('requestChangesBtn').onclick=()=>reviewTask(false);$('cancelTaskBtn').onclick=async()=>{if(!state.selectedTaskId)return;try{await api(`/api/tasks/${encodeURIComponent(state.selectedTaskId)}/cancel`,{method:'POST',body:JSON.stringify({reason:$('taskFeedback').value||'Cancelled by operator.'})});$('taskDialog').close()}catch(e){toast(e.message)}};
async function reviewTask(accepted){if(!state.selectedTaskId)return;const feedback=$('taskFeedback').value.trim()||(accepted?'Accepted.':'Changes requested.');try{await api(`/api/tasks/${encodeURIComponent(state.selectedTaskId)}/review`,{method:'POST',body:JSON.stringify({accepted,feedback})});$('taskDialog').close()}catch(e){toast(e.message)}}
load().catch(e=>{toast(e.message);$('connection').textContent='offline'});
